language: python
python:
  - 3.7.1
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install pytest-cov
install:
  - pip install -r requirements.txt
script: python -m pytest --cov-report=xml --cov=. tests/ # run tests
after_success:
  - codecov # submit coverage
